//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//



LOAD_SUITE te_xmlomxclient

START_TESTCASE MM-AUDIO-OMX-FILESINKSRC-001-HP
	START_TEST_BLOCK 30 te_xmlomxclient c:\te_xmlomxclient.ini
		CREATE_OBJECT OmxXmlTestWrapper InstanceName
		COMMAND	InstanceName New c:\te_omx_filesinksrc.xml
		COMMAND InstanceName RunTest Testcase1
	END_TEST_BLOCK
END_TESTCASE MM-AUDIO-OMX-FILESINKSRC-001-HP


